# Generated by Django 4.2.4 on 2023-08-14 04:59

from django.db import migrations, models
import fetch_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[fetch_app.models.Sample.name_check, fetch_app.models.Sample.name_check_len])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
