# Generated by Django 4.2.4 on 2023-08-14 05:55

from django.db import migrations, models
import fetch_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='email',
            field=models.EmailField(max_length=254, validators=[fetch_app.models.Sample.email_check, fetch_app.models.Sample.email_domain_check]),
        ),
    ]
